### ISSUE TITLE
Problem with Ch2 TPI and negative consumptions

### ISSUE THREAD

**Issue by rickecon** [MaxGhenis/OGprimer_exercises#1]
@MaxGhenis. I think I found the problem with your TPI code. Let me know if you want to discuss anytime over Zoom meeting. If not, then here is the somewhat quick answer.

The marginal utilities in your Euler errors are being violated by negative consumption values associated with the root finder’s guesses for `b2` and `b3`. There are two ways to solve the household’s problem over the time path. One is a constrained minimizer over the following optimization problem:

![image](https://user-images.githubusercontent.com/4317690/86397065-59575780-bc60-11ea-937c-38023a63be03.png)

The other is the two-equation root finder problem characterized by the two Euler equations, which are derived from the maximization (minimization) problem above.

![image](https://user-images.githubusercontent.com/4317690/86397503-2e213800-bc61-11ea-8abb-612212c5dbbe.png)

The root finder problem is much faster than the constrained minimization problem. Also, you can show that the solution is always an interior solution so that the three inequality constraints never bind. However, the root finder doesn’t know that. So you need to add something to keep the root finder going in the right direction if it ever chooses a (b2, b3) combination that generates a negative consumption somewhere in the  resulting (c1, c2, c3) vector.

A very cheap fix that I have in my code for chapter 2 is simply the following code.
```python
def get_c(bvec, nvec, rvec, wvec):
  bvec_s = np.hstack((0.0, bvec))
  bvec_sp1 = np.hstack((bvec, 0.0))
  cvec = wvec * nvec + (1 + rvec) * bvec_s - bvec_sp1
  cvec_cstr = cvec <= 0

  return cvec, cvec_cstr
```    
Then, you use this when you create your Euler errors in the time path. In particular, you need to make sure that all the consumption values that go into a marginal utility are positive.
```python
def marg_util_c(cvec, sigma):
  cvec_cstr = cvec <= 0
  cvec[cvec_cstr] = 9999.
  marg_util_vec = cvec ** (-sigma)

  return marg_util_vec
```
Finally, I add one more layer to make sure that the Euler errors are penalized in the right place. However, I am not sure whether this next step is necessary. We use a more precise and sophisticated method as the model gets more complex. This is just a cheap fix.
```python
def Eul_err_vec(cvec, rvec, wvec, beta, sigma)
  cvec_cstr = cvec <= 0
  mu_c = marg_util_c(cvec, sigma)
  eul_errs = (beta * (1 + rvec[1:]) * mu_c[1:]) - mu_c[:-1]
  eul_errs[cvec_cstr[:-1]] = 9999.
  eul_errs[cvec_cstr[1:]] = 9999.

  return eul_errs
```
Think of what this is doing. `c_2` could be negative because either `b_2` was too small or because `b_3` was too big. So we need to penalize any Euler equations in which `c_2` is used. As the root finder is searching for the combination of `b2` and `b3` that simultaneously solves both Euler equations, it might look at values that violate the nonnegativity constraints on `c1`, `c2`, and `c3`. We want the errors on those guesses to be big so the root finder moves away from them. We know that the answer is an interior solution.

We have a more sophisticated fix that we use in future chapters and in OG-USA. But this one should fix your TPI. I am happy to take you through the more sophisticated fix whenever you like.

cc: @jdebacker

**Comment by MaxGhenis** [comment]
Thank you @rickecon! I added the consumption constraints in https://github.com/MaxGhenis/OGprimer_exercises/commit/0f450e20e32bbf20c8aa1733136652d066d9181d, but actually I don't think that was the issue. When I was revising the code, I saw that I inadvertently had one of my `1+r` terms improperly paren'd, so one of my marginal utilities was getting multiplied by `r` instead. Fixing that caused the TPI to stabilize.

I think seeing your code in terms of consumption made the concept of equalizing marginal utility across periods finally click. This is shown clearly in equation 2.9 and we discussed it in that part of our walk-through, but that intuition left my brain when I was focusing on the TPI mechanics, and I got bogged down in the components of consumption in each period.

It's also cool to see the Euler errors vectorized. I can see how moving toward the S-period model will force cleaner code.

Appreciate your help!
